"""Emit Lean 4 stubs for Wang tilesets and tileset-defined SFTs."""

from __future__ import annotations

from typing import Sequence

from .tilesets import WangTile


def emit_tileset_stub(tiles: Sequence[WangTile], name: str) -> str:
    """Lean 4 stub for a Wang tileset.

    Generates a `def name : List ((α × α) × (α × α))` (north/south/east/west
    tuples) along with a placeholder `Subshift` definition matching the
    project's `mkSFT` convention. The user adapts `α` to their alphabet
    encoding (here `String` is used as a stand-in).
    """
    n_tiles = len(tiles)
    tile_lines = ",\n  ".join(
        f'  -- t{i+1}\n  (("{t.N}", "{t.S}"), ("{t.E}", "{t.W}"))'
        for i, t in enumerate(tiles)
    )
    return f"""/-- {name}: a Wang tileset with {n_tiles} tiles.
Tile format: `((N, S), (E, W))`.

This is a stub generated by symdyn-tilings. To use it inside the
project's `mkSFT` framework, encode each tile as a `Pattern` over a
size-1 window and translate the matching constraints to a finset of
allowed 2-cell patterns.
-/
def {name}_tiles : List ((String × String) × (String × String)) := [
{tile_lines}
]

/-- {name}: 2D SFT defined by `{name}_tiles` (stub).

Replace `Subshift.univ` with `mkSFT F L` once the encoding of horizontal
and vertical adjacency rules as a `Finset (Pattern α F)` is in place.
-/
def {name} : Subshift String 2 :=
  Subshift.univ String 2
"""
