"""Emit Lean 4 stubs for symbolic-dynamics objects."""

from __future__ import annotations

from typing import Sequence


def emit_subshift_stub(
    alphabet: Sequence[str], forbidden: Sequence[Sequence[str]], name: str
) -> str:
    """Lean 4 stub for an SFT defined by `forbidden` factors over `alphabet`.

    The stub uses the project's canonical `dependencies/Subshift.lean`
    types (`Lat`, `Pattern`, `mkSFT`). It is meant to be pasted into a
    file under `SymbolicDynamics/`, where the user will adapt the
    `α` alphabet type and the encoding of forbidden factors as
    `Finset (Pattern α F)`.
    """
    alphabet_card = len(alphabet)
    forbidden_str = "\n".join(
        f"-- forbidden factor #{i}: {list(f)}"
        for i, f in enumerate(forbidden)
    )
    return f"""/-- {name}: 1D SFT over an alphabet of size {alphabet_card}.

Forbidden factors:
{forbidden_str}

This is a stub generated by symdyn-shifts. The full definition needs to
fix the alphabet type (e.g. `Fin {alphabet_card}`) and encode the
forbidden factors as a `Finset (Pattern α F)` for the appropriate
window `F`.
-/
def {name} : Subshift (Fin {alphabet_card}) 1 :=
  -- TODO: encode the forbidden factors as a Finset (Pattern α F)
  -- and replace `Subshift.univ` with `mkSFT F L`.
  Subshift.univ (Fin {alphabet_card}) 1
"""
