name = "SymbolicDynamics"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["SymbolicDynamics"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.26.0-rc1"

[[lean_lib]]
name = "SymbolicDynamics"
roots = ["SymbolicDynamics", "papers.HochmanMeyerovitch.HochmanMeyerovitch", "papers.HochmanMeyerovitch.OpenProblems", "papers.DurandGamardGrandjean.DGG", "dependencies.ComputableRat", "dependencies.Subshift", "dependencies.Box", "dependencies.LocallyAdmissible", "dependencies.GloballyAdmissible", "dependencies.Entropy", "dependencies.Computable", "dependencies.InvariantMeasure", "dependencies.InvMeasureCompactness", "dependencies.NbarComputable", "dependencies.IrreducibleConsequences", "dependencies.FactorMap", "dependencies.Percolation", "dependencies.KariCulik", "dependencies.DGG", "axioms.InvariantMeasure", "axioms.Computability", "axioms.Irreducible", "axioms.KariCulik", "axioms.DGG", "openProblems.WeissConjecture.WeissConjecture", "openProblems.OddShiftSoficity.OddShiftSoficity", "openProblems.KariCulikEntropy.KariCulikEntropy", "openProblems.KariCulikEntropy.generated_questions.Computability", "openProblems.KariCulikEntropy.generated_questions.Algebraicity", "openProblems.KariCulikEntropy.generated_questions.DGGQ1", "openProblems.KariCulikEntropy.generated_questions.DGGQ2", "openProblems.KariCulikEntropy.generated_questions.DGGQ3", "trajectories.KariCulikEntropyComputableStatement.Attempt_1_rightRE_via_HM"]
